### ISSUE TITLE
Install fails on linux

### ISSUE THREAD

**Issue by ChariseWalraven** [mklement0/ttab#19]
Hi there,

I know this is a module for mac, but could you please not throw an exception on installation when the OS is not a Mac?

Whenever I try to install my dependencies, I cannot complete the installation, because it throws me an error in the process of installing because I'm not on a mac and then exits the installation.

I am definitely sure this is ttab, because it works fine when i remove the dependency on a ubuntu distro and then intall the dependencies again. 

![image](https://user-images.githubusercontent.com/31189070/48081142-a1a24600-e1ef-11e8-9aa1-7dc903ebc6c7.png)

Maybe it's possible to show an info message instead of an outright error and just skip the installation if the system is not a Mac?

**Comment by mklement0** [comment]
`ttab`'s `package.json` file by design indicates that the package is only supported on macOS:

https://github.com/mklement0/ttab/blob/a2f01f1c048c62cb6b28ad8085fc222f2659311e/package.json#L6-L8

I'm not familar with `yarn`, but it sounds like if you reference `ttab` from your project's _optional_ dependencies (`"optionalDependencies"`) - just as `fsevents` appears to be declared as in yoru screen shot - the problem should go away.

`yarn install --ignore-platform` may work too, though it may be too blunt a tool.

Let me know if that doesn't help.
